### ISSUE TITLE
error[E0308]: mismatched types

### ISSUE THREAD

**Issue by mabushey** [pemistahl/lingua-rs#41] opened 2022-02-21 19:53 UTC
Hello,

This crate looks awesome! I plan on using it to detect languages of subtitles. Thanks for writing this crate! I added it to cargo.toml, but I get this on cargo build:

```
error[E0308]: mismatched types
   --> /home/michael/.cargo/registry/src/github.com-1ecc6299db9ec823/lingua-1.3.2/src/json.rs:265:32
    |
262 | fn get_language_models_directory(language: Language) -> Dir<'static> {
    |                                                         ------------ expected `include_dir::Dir<'static>` because of return type
...
265 |         Language::Afrikaans => AFRIKAANS_MODELS_DIRECTORY,
    |                                ^^^^^^^^^^^^^^^^^^^^^^^^^^ expected struct `include_dir::Dir`, found struct `include_dir::dir::Dir`
    |
    = note: perhaps two different versions of crate `include_dir` are being used?

For more information about this error, try `rustc --explain E0308`.
```

Here is my full cargo.toml dependency list:
```
clap = { version = "3.0", features = ["derive"] }
regex = "1"
tmdb = "3.0.0"
log = "0.4"
pretty_env_logger = "0.4.0"
walkdir = "2"
dirs = "3.0"
serde = { version = "1.0", features = ["derive"]   }
serde_yaml = "0.8"
md-5 = "0.9"
unicode-truncate = "0.2.0"
lazy_static = "1.4.0"
common-path = "1.0.0"
lingua = "1.3.2"
```
```
$ rustc --version
rustc 1.58.1 (db9d1b20b 2022-01-20)
```

I'm kind of a Rust noob so I'm not sure how to fix this...

**Comment by pemistahl** [comment] 2022-02-22 09:53
Hello Michael, thank you very much for trying my library.

I'm sorry, the compilation problem you are describing is actually my fault. I updated the `include_dir` dependency in the language model crates but forgot to tell the `lingua` crate that it should keep using the older version of the `include_dir` dependency for Lingua version 1.3.2. The cause was a wrong declaration of the language model crate versions in the `Cargo.toml` file. 

I've just committed a fix for this and made a new Lingua release 1.3.3. Please use this new release and the compilation problem will disappear.

**Closed by pemistahl** 2022-02-22 09:53 UTC

**Comment by mabushey** [comment] 2022-02-23 03:27
Thank you! I have it working now, and it's working quite well.

isocode.rs appears to be a to_upper and to_lower system that only works for valid 2 letter and 3 letter Country abbreviations. Do you know the best way to get the proper IsoCode639_3 code from the full name that LanguageDetector returns? I could probably just grep/regex the isocode.rs file into a rust hashmap (ie ("Russian", "RUS"), etc as the language name is in the comment.

Have a great day!

**Comment by pemistahl** [comment] 2022-02-23 08:25
> Do you know the best way to get the proper IsoCode639_3 code from the full name that LanguageDetector returns?

Please take a look at the [API docs](https://docs.rs/lingua/latest/lingua/enum.Language.html#method.iso_code_639_1). There are methods that return the ISO codes for a given language.
